poll/authen/urls.py
from django.urls import path
from authen import views

urlpatterns = [
    path('login/', views.Login.as_view(), name='authen_login'),
    path('logout', views.Logout.as_view(), name='authen_logout'),
]

poll/main/urls.py
from django.urls import path
from main import views

from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.Index.as_view()),
    path('question/<slug>', login_required(views.Question.as_view()), name='question')
]

poll/poll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authen/', include('authen.urls')),
    path('', include('main.urls')),
]

poll/authen/models.py
from django.db import models

# Create your models here.

poll/main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Question(models.Model):
    slug = models.SlugField()
    content = models.CharField(max_length = 1024)

    def __str__(self):
        return self.content



class Answer(models.Model):
    question = models.ForeignKey('Question', on_delete=models.CASCADE)
    choice = models.ForeignKey('Choice', on_delete=models.CASCADE)
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=True)



class Choice(models.Model):
    question = models.ForeignKey('Question', on_delete = models.CASCADE)
    content = models.CharField(max_length = 256)
    
    @property
    def answer_count(self):
        return Answer.objects.filter(
        question = self.question,
        choice = self
        ).count()

    def __str__(self):
        return "{} - {}".format(self.question.content[:50], self.content)
    

poll/main/forms.py
from django import forms
from main import models

class AnswerForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields = ['choice']

poll/authen/views.py
from django.shortcuts import render
from django.contrib.auth.views import (
    LoginView,
    LogoutView as Logout
)    
# Create your views here.

class Login(LoginView):
    template_name = 'authen/login.html'
    redirect_authenticated_user = True

poll/main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import (
  ListView,
  DetailView,
  FormView
)
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import PermissionRequiredMixin

from main import models, forms

# Create your views here.
class Index(ListView):
  model = models.Question
  template_name = 'main/index.html'

class Question(PermissionRequiredMixin, SingleObjectMixin, FormView):
  model = models.Question
  template_name = 'main/question.html'
  form_class = forms.AnswerForm
  permission_required = 'add_answer'

  # def get_context_data(self, **kwargs):
  #   data = super().get_context_data(**kwargs)
  #   data['answer'] = models.Answer.objects.get(
  #     question = self.get_object(),
  #     user = self.request.user
  #   )
  #   return data

  def form_valid(self, form):
    obj = form.save(commit = False)
    obj.question = self.get_object()
    obj.user = self.request.user
    obj.save()
    return HttpResponseRedirect('/')

  def post(self, request, *args, **kwargs):
    self.object = self.get_object()
    return super().post(request, *args, **kwargs)

  def get(self, request, *args, **kwargs):
    self.object = self.get_object()
    context = self.get_context_data(object=self.object)
    return self.render_to_response(context)

poll/templates/authen/login.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">

        <div class="row">
            <div class="col s6">
            <div class="card">
                <div class="card-content orange-text">
               
                    <span class="card-title">Login</span>
                    <form action="" method="post">

                        {%  csrf_token %}

                        {% for field in form %}                        
                            <div class="input-field">
                                {{ field }}
                            </div>
                        {% endfor %}

                        <button class="btn waves-effect waves-light" type="submit" name="action">
                            Login
                          </button>
                                
                    </form>

                </div>
            </div>
            </div>
        </div>
            
    </div>

{% endblock %}

poll/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Poll</title>

     <!-- Compiled and minified CSS -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

     <!-- Compiled and minified JavaScript -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

     
</head>
<body>
    
    {% block content %} {% endblock %}
    
</body>
</html>

poll/templates/main/components/navbar.html
  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Poll</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="#">Questions</a></li>
        <li>

          {% if request.user.is_authenticated %}
          <a href="{% url 'authen_logout' %}">Logout</a>
          {% else %}
            <a href="{% url 'authen_login' %}">Login</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </nav>

poll/templates/main/index.html
{% extends 'base.html' %}
{% block content %}

{% include 'main/components/navbar.html' %}


<div class="container">
    <div class="row">
        <h1>Trending Questions</h1>
    </div>
    <div class="row">
        <div class="col-6">
            <div class="collection">        
                {% for question in question_list %}   <!-- question_list is by default context made by models which is being rendered in the html file-->
                                                    <!-- it can also be passed as a context in the views.py file as context_name = 'question_list' -->
                    <a href="{% url 'question' question.slug %}" class="collection-item">
                        {{ question.content }}
                    </a>
                {% endfor %}
            </div>              
        </div>
    </div>
</div>
{% endblock %}

poll/templates/main/question.html
{% extends 'base.html' %}

{% block content %}

  {% include 'main/components/navbar.html' %}

  <div class="container">

    <div class="row">
      <h4>{{question.content}}</h4>
    </div>

    <form action="" method="post">
      {% csrf_token %}

      <div class="row">
        <div class="col-6">
          <div class="collection">
            {% for choice in question.choice_set.all %}
              <div class="collection-item">
                {% if answer %}
                  {{choice.content}} ({{choice.answer_count}})
                  {% if answer.choice.id == choice.id %}
                    <i class="material-icons">check</i>
                  {% endif %}
                {% else %}
                  <label>
                    <input class="with-gap" name="choice" type="radio" value="{{choice.id}}" />
                    <span>{{choice.content}}</span>
                  </label>
                {% endif %}
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
  

        <div class="row">
          <button class="btn waves-effect waves-light" type="submit" name="action">
            Submit
            <i class="material-icons right">send</i>
          </button>
        </div>
      

      <div class="row">
        <p class="red">
          <ul>
            {% for error in form.errors %}
              <li>
                {{error}}
              </li>
            {% endfor %}
          </ul>
        </p>
      </div>
    </form>

  </div>

{% endblock %}